### ISSUE TITLE
[Task]: Implement State in Go

### ISSUE THREAD

**Issue by damccorm** [apache/beam#22736]
### What needs to happen?

Part of #20510 - designed here - https://docs.google.com/document/d/1rcKa1Z6orDDFr1l8t6NA1eLl6zanQbYAEiAqk39NQUU/edit?usp=sharing

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-go

**Comment by damccorm** [comment]
Generally, things that need to be done for this to be called complete:

**Phase 1 - MVP**

- [ ] User experience changes - make it possible to declare one or more state member variables. Perform validation. Plumb that information through to graph construction/execution. No/op, and temporarily throw a validation exception until more is implemented.
- [ ] Execution changes - when appropriate, pass in a fully hydrated state provider that knows how to handle ValueState (with set and clear operations) and can talk to the state api. Update validation to allow value state types.
- [ ] Integration test.

**Phase 2 - Full support**

Following pattern established in part 1, implement:

- [ ] BagState + integration test
- [ ] CombiningState + integration test
- [ ] OrderedListState + integration test
- [ ] MapState + integration test
- [ ] Prefetch
