### ISSUE TITLE
[Task]: Umbrella issue of Test breakage due to upstream docker image using debian 12 (bookworm) 

### ISSUE THREAD

**Issue by Abacn** [apache/beam#27154]
### What needs to happen?

We have seen a couple of test failures due to base image switched to use Debian 12 (bookworm). This issue is created to track these changes and how it fixed. In the case we pin old Debian version, we may need to come back and unpin them when dependencies support bookworm

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
#26988 Website precommit failure due to debian bookworm dropped support of Node 10. Fixed by upgrading Node->14

**Comment by Abacn** [comment]
#27019 Python37 PostCommit failure due to azure-cli not yet supports bookworm. #27153 pins bullseye. Need to unpin it once azure-cli supports bookworm

**Comment by Abacn** [comment]
Not seen recently, close this for now
