### ISSUE TITLE
[Epic]: Ensure all exception blocks in Tier 1 Beam IOs are safe

### ISSUE THREAD

**Issue by damondouglas** [apache/beam#28080]
### What needs to happen?

This issue serves as a parent tracker to fix:

For both Python and Java,

Inspect all exception blocks in IOs, and ensure that they either properly handle the exception, or they rethrow the exception to be handled by the runner.

There may be rare cases where it is appropriate to not do either of the above, but those should be heavily scrutinized.

#### Tier 1 IOs

The Tier 1 IOs include:
- BigQueryIO
- BigTableIO
- PubSubIO
- FileIO
- SpannerIO
- KafkaIO
- JdbcIO

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by damondouglas** [comment]
.take-issue

**Comment by johnjcasey** [comment]
@damondouglas can we close this, or is there still work to do?
