### ISSUE TITLE
[Bug]: Roadmap page is out of date. 

### ISSUE THREAD

**Issue by aaltay** [apache/beam#28342]
### What happened?

https://beam.apache.org/roadmap/ is out of date. We could update or clean up the roadmap page.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [X] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by liferoad** [comment]
@kennknowles FYI.

**Comment by rakeshcusat** [comment]
@kennknowles / @aaltay where we can find the updated roadmap?

**Comment by liferoad** [comment]
@damccorm

**Comment by rakeshcusat** [comment]
I am more than happy to update the roadmap page as long as I can find it in some document/email thread.

**Comment by liferoad** [comment]
I think we can at least update these:

Python 3 support: we already support Python 3.12 and sunset Python 3.8. Supporting 3.13 is on the roadmap.

Java 17 support: this is already supported. Java 21 is on the roadmap.

You can find more information about the versions that support Python 3.12 and Java 17 here: https://github.com/apache/beam/blob/master/CHANGES.md

For Go, this is no active development now.

Feel free to raise a PR. We can discuss over there. Thanks!

**Comment by rakeshcusat** [comment]
.take-issue

**Comment by rakeshcusat** [comment]
@liferoad here is the initial [PR](https://github.com/apache/beam/pull/34330) Let's provide more details around the jira tickets and relevant information on the PR.

**Comment by liferoad** [comment]
Fixed by https://github.com/apache/beam/pull/34330
