### ISSUE TITLE
[Task]: Also remove META-INF for excluded transitive dependencies in Beam vendored dependencies

### ISSUE THREAD

**Issue by Abacn** [apache/beam#28919]
### What needs to happen?

We vendor a few dependencies (nowadays only guava, grpc, calcite), where some transitive dependency were explicitly excluded, e.g.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by goutamadwant** [comment]
Hi @Abacn, I checked the current vendoring setup and #28919 still appears relevant for the Calcite/gRPC/Guava artifacts. Is this task still required? If so, would you prefer a generic VendorJavaPlugin solution with JAR-content regression tests, or per-vendor metadata exclusions? I can work on thos. thanks!
