### ISSUE TITLE
[Feature Request]: Add custom counters tracking bytes read and written from the Google Cloud Storage in the GcsFileSystem

### ISSUE THREAD

**Issue by tilgalas** [apache/beam#31492]
### What would you like to happen?

In Java, whenever a PTransform such as TextIO uses a "gs://" schema, the bytes that are read and written are reported to a custom per-bucket metric. This feature should be gated behind a set of opt-in flags, with no change to the default behavior.
A related issue for the Python SDK is #31465

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tilgalas** [comment]
.take-issue
