### ISSUE TITLE
[Feature Request]: Add support in BQ IO to emit dataset they are accessing for lineage tracking

### ISSUE THREAD

**Issue by rohitsinha54** [apache/beam#31804]
### What would you like to happen?

BQ IOs should emit dataset they are accessing as lineage information through StringSet metric. 

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [X] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by rohitsinha54** [comment]
.take-issue
